export const getSearchData = () => {
  return [
    {
      id: "01",
      title: "Loan Dispute",
      content: "Customer complaint about incorrect loan interest rate.",
      category: "Loan",
      decision: "Upheld",
      company: "Barclays Bank Plc",
      date: "2022-11-08",
    },
    {
      id: "02",
      title: "Credit Card Fraud",
      content: "Unauthorized transaction on credit card.",
      category: "Credit Card",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2024-02-15",
    },
    {
      id: "03",
      title: "Account Closure Issue",
      content: "Customer dissatisfied with account closure process.",
      category: "Current Account",
      decision: "Partially Upheld",
      company: "Lloyds Bank",
      date: "2024-01-05",
    },
    {
      id: "04",
      title: "Insurance Claim",
      content: "Insurance claim dispute regarding coverage.",
      category: "Insurance",
      decision: "Upheld",
      company: "Aviva Plc",
      date: "2024-03-22",
    },
    {
      id: "05",
      title: "Mortgage Payment Issue",
      content: "Incorrect mortgage payment details provided.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Santander UK",
      date: "2024-04-10",
    },
    {
      id: "06",
      title: "Savings Account Interest",
      content: "Interest not applied correctly to savings account.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2022-12-17",
    },
    {
      id: "07",
      title: "PPI Complaint",
      content: "Mis-sold payment protection insurance.",
      category: "PPI",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2024-01-28",
    },
    {
      id: "08",
      title: "Loan Overpayment",
      content: "Overpayment on loan not refunded.",
      category: "Loan",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2024-03-01",
    },
    {
      id: "09",
      title: "Bank Fees Dispute",
      content: "Dispute regarding excessive overdraft fees.",
      category: "Overdraft",
      decision: "Upheld",
      company: "Metro Bank",
      date: "2023-05-06",
    },
    {
      id: "10",
      title: "Unauthorised Account Activity",
      content: "Customer noticed unauthorised withdrawals.",
      category: "Current Account",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2023-02-20",
    },
    {
      id: "11",
      title: "Missed Direct Debit",
      content: "Bank missed scheduled direct debit payment.",
      category: "Direct Debit",
      decision: "Upheld",
      company: "TSB Bank",
      date: "2023-04-15",
    },
    {
      id: "12",
      title: "Delay in Fund Transfer",
      content: "Delay in transferring funds between accounts.",
      category: "Funds Transfer",
      decision: "Partially Upheld",
      company: "Barclays Bank Plc",
      date: "2023-03-25",
    },
    {
      id: "13",
      title: "Incorrect Credit Report",
      content: "Bank reported incorrect details on credit report.",
      category: "Credit Report",
      decision: "Upheld",
      company: "Experian Plc",
      date: "2023-05-12",
    },
    {
      id: "14",
      title: "Fraudulent Loan Application",
      content: "Fraudulent loan taken out in customer's name.",
      category: "Loan",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2023-01-18",
    },
    {
      id: "15",
      title: "Lost Cheque Issue",
      content: "Cheque lost during bank processing.",
      category: "Cheque",
      decision: "Upheld",
      company: "Halifax",
      date: "2022-12-30",
    },
    {
      id: "16",
      title: "Card Decline Error",
      content: "Debit card declined during a transaction.",
      category: "Debit Card",
      decision: "Rejected",
      company: "HSBC Holdings",
      date: "2023-04-22",
    },
    {
      id: "17",
      title: "Foreign Transaction Charges",
      content: "Customer disputes unexpected foreign transaction charges.",
      category: "Credit Card",
      decision: "Partially Upheld",
      company: "Santander UK",
      date: "2023-02-08",
    },
    {
      id: "18",
      title: "Standing Order Cancellation",
      content: "Standing order cancelled without customer consent.",
      category: "Standing Order",
      decision: "Upheld",
      company: "NatWest Bank",
      date: "2023-03-14",
    },
    {
      id: "19",
      title: "Mortgage Interest Rate Dispute",
      content: "Incorrect interest rate applied to mortgage.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-01-11",
    },
    {
      id: "20",
      title: "ATM Withdrawal Error",
      content: "ATM did not dispense cash but account debited.",
      category: "ATM",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-05-19",
    },
    {
      id: "21",
      title: "Loan Approval Delay",
      content: "Loan approval process delayed beyond promised timeline.",
      category: "Loan",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2023-05-05",
    },
    {
      id: "22",
      title: "Incorrect Mortgage Balance",
      content: "Customer reported an incorrect mortgage balance.",
      category: "Mortgage",
      decision: "Rejected",
      company: "Santander UK",
      date: "2023-02-11",
    },
    {
      id: "23",
      title: "Cheque Processing Delay",
      content: "Cheque took too long to be processed.",
      category: "Cheque",
      decision: "Upheld",
      company: "Metro Bank",
      date: "2023-04-28",
    },
    {
      id: "24",
      title: "Savings Interest Discrepancy",
      content: "Incorrect interest credited to savings account.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2023-03-13",
    },
    {
      id: "25",
      title: "Late Loan Payment",
      content: "Late payment notification was not sent.",
      category: "Loan",
      decision: "Rejected",
      company: "NatWest Bank",
      date: "2023-05-20",
    },
    {
      id: "26",
      title: "ATM Transaction Error",
      content: "ATM deducted money but did not dispense cash.",
      category: "ATM",
      decision: "Rejected",
      company: "Santander UK",
      date: "2023-06-14",
    },
    {
      id: "27",
      title: "Credit Card Application Rejection",
      content: "Customer's credit card application rejected unfairly.",
      category: "Credit Card",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-07-04",
    },
    {
      id: "28",
      title: "Mortgage Payment Miscalculation",
      content: "Bank incorrectly calculated the mortgage payments.",
      category: "Mortgage",
      decision: "Upheld",
      company: "HSBC Holdings",
      date: "2023-06-09",
    },
    {
      id: "29",
      title: "Fraudulent Credit Card Transaction",
      content: "Unauthorized credit card transaction detected.",
      category: "Credit Card",
      decision: "Upheld",
      company: "Lloyds Bank",
      date: "2023-07-20",
    },
    {
      id: "30",
      title: "Delay in Loan Approval",
      content: "Loan approval delayed due to incorrect documentation.",
      category: "Loan",
      decision: "Partially Upheld",
      company: "NatWest Bank",
      date: "2023-08-01",
    },
    {
      id: "31",
      title: "Cheque Cleared with Wrong Amount",
      content: "Cheque was cleared for an incorrect amount.",
      category: "Cheque",
      decision: "Upheld",
      company: "Halifax",
      date: "2023-06-25",
    },
    {
      id: "32",
      title: "PPI Rejection Complaint",
      content: "Complaint about rejection of PPI claim.",
      category: "PPI",
      decision: "Rejected",
      company: "Barclays Bank Plc",
      date: "2023-08-10",
    },
    {
      id: "33",
      title: "Overdraft Fees Dispute",
      content: "Customer disputes high overdraft fees.",
      category: "Overdraft",
      decision: "Partially Upheld",
      company: "Metro Bank",
      date: "2023-07-15",
    },
    {
      id: "34",
      title: "Savings Account Closure Issue",
      content: "Customer faced delays in closing a savings account.",
      category: "Savings Account",
      decision: "Upheld",
      company: "Santander UK",
      date: "2023-08-21",
    },
    {
      id: "35",
      title: "Unauthorized Loan Application",
      content: "Fraudulent loan application in customer's name.",
      category: "Loan",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2023-07-28",
    },
    {
      id: "36",
      title: "Debit Card Decline Issue",
      content: "Customer's debit card declined without reason.",
      category: "Debit Card",
      decision: "Partially Upheld",
      company: "HSBC Holdings",
      date: "2023-08-05",
    },
    {
      id: "37",
      title: "ATM Fee Dispute",
      content: "Customer disputes high ATM withdrawal fees.",
      category: "ATM",
      decision: "Upheld",
      company: "Nationwide Building Society",
      date: "2023-07-11",
    },
    {
      id: "38",
      title: "Funds Transfer Delay",
      content: "Delay in transferring funds between accounts.",
      category: "Funds Transfer",
      decision: "Partially Upheld",
      company: "NatWest Bank",
      date: "2023-06-29",
    },
    {
      id: "39",
      title: "Lost Cheque Dispute",
      content: "Customer's cheque was lost in transit.",
      category: "Cheque",
      decision: "Upheld",
      company: "Halifax",
      date: "2023-07-30",
    },
    {
      id: "40",
      title: "Incorrect Direct Debit",
      content: "Customer charged an incorrect amount via direct debit.",
      category: "Direct Debit",
      decision: "Rejected",
      company: "Lloyds Bank",
      date: "2024-08-14",
    },
  ];
};
